### ISSUE TITLE
Change Default Admin Web Interface Port

### ISSUE THREAD

**Issue by ab-tools** [ugoviti/izpbx#87] opened 2024-12-21 17:53 UTC
Hello Ugo,

first thanks a lot for your great work on this project!

FreePBX works well for me in the Docker container, but I really would like to change the default port of the admin web interface.

I expected this to be possible in the `.env` file by changing these two variable e. g. like this:
```
APP_PORT_HTTP=8181
APP_PORT_HTTPS=4431
```

But whatever I set them to, this seems not to have any effect, `httpd` always binds to port `80` nonetheless.

When I connect to the container I also see `Listen 80` in `/etc/httpd/conf/httpd.conf`.

So what are these `APP_PORT_*` variables for and what is the best way to permanently change the admin web interface port to something else than 80?

Probably just a simple thing I miss. :-)

I'm using version 20.16.13 at the moment in case relevant.

Best regards and thanks in advance for any tip on this
Andreas

**Comment by ugoviti** [comment] 2024-12-28 16:50
Hi,

I just tried with a new fresh install and can't reproduce your problem:

```
$ grep ^APP_PORT_HTTP .env 
APP_PORT_HTTP=8080
APP_PORT_HTTPS=8443


$ docker exec -it izpbx bash
(izPBX)[root@nbk21.quantico: /]# grep ^Listen /etc/httpd/conf/httpd.conf /etc/httpd/conf.d/virtual.conf
/etc/httpd/conf/httpd.conf:Listen 8080
/etc/httpd/conf.d/virtual.conf:Listen 8443 https

# netstat -atpun | grep LISTEN | grep httpd        
tcp6       0      0 :::8080                 :::*                    LISTEN      1003/httpd          
tcp6       0      0 :::8443                 :::*                    LISTEN      1003/httpd  
```
try with 20.16.16

closing for now

Kind regards

**Closed by ugoviti** 2024-12-28 16:50 UTC
